behaviors:
  Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0005
      beta: 0.005
      epsilon: 0.4
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 5
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 6000000
    time_horizon: 64
    summary_freq: 50000
